use time.Duration instead of durationNanos
mongodb/mongo-go-driver pull request #1120
Opened 2022-11-06 19:07 UTC by jtagcat

Same as #1105

```
OK make fmt
OK make lint
make test: go.mongodb.org/mongo-driver/mongo/integration/unified: no such command: 'configureFailPoint'
(make test fails on master with same result)
make test-race: same result as make test
```

2022-12-13 15:35 UTC, qingyang-hu reviewed
The replacement seems reasonable though it is backward-breaking.
Instead, in v1.x, we can deprecate the current fields while adding new fields named `Duration` that are type `time.Duration`.
We can retire these `DurationNanos` fields in the upcoming v2 driver.

2022-12-14 09:20 UTC, jtagcat commented on mongo/integration/unified/client_entity.go
> +		AppendInt64("duration", int64(evt.Duration)).
How is the bson used? Why do other events not use Duration (non-exhaustive)?

2023-02-15 20:02 UTC, matthewdale requested changes
Hey @jtagcat sorry about the slow review and thanks for the edits! I have one required change, but it otherwise looks great!

2023-03-01 03:16 UTC, matthewdale commented
Closing in favor of https://github.com/mongodb/mongo-go-driver/pull/1193

2023-03-01 03:16 UTC, closed without merging