GODRIVER-2753 Integration with oss-fuzz fuzzing service
mongodb/mongo-go-driver pull request #1170
Opened 2023-02-01 16:45 UTC by manunio

GODRIVER-2753

## Summary
This PR adds a cmd to build zip file of seed corpus for fuzzing to be used by oss-fuzz.

## Background & Motivation
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/9528, it contains necessary logic from an OSS-Fuzz perspective to integrate mongo-go-driver.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects, you can find more details in our [FAQ](https://google.github.io/oss-fuzz/faq/).

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

2023-02-08 19:51 UTC, prestonvasquez requested changes
Thank you @manunio for putting this together, the team is very appreciative. I have some initial feedback, please reach out if you have any questions. 

As for the emails,

- "primary_contact": dbx-go@mongodb.com
- "auto_cc": 
    - qingyang.hu@mongodb.com
    - matt.dale@mongodb.com
    - kevin.albertson@mongodb.com
    - preston.vasquez@mongodb.com

2023-02-08 19:51 UTC, prestonvasquez commented on bson/bson_fuzz_corpus_common.go
> +type TestCase struct {
There is no need for this common file or to export any of this data. Can we unexport it and just duplicate the "findJSONFilesInDir" and "JsonToBytes" functions in the cmd/build-oss-fuzz-corpus/main.go ?

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +	seed_corpus := os.Args[1]
Rename this to "seedCorpus", [mixedCaps](https://go.dev/doc/effective_go#mixed-caps) is the convention.

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +	}
What is this checking for? If it's to see if the corpus has a zip extension can you do it this way:

```suggestion
	if filepath.Ext(seedCorpus) != ".zip" {
		log.Fatalf("expected zip file <corpus>.zip, got %s", seedCorpus)
	}
```

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +	zip_file, err := os.Create(seed_corpus)
Rename this to "zipFile", [mixedCaps](https://go.dev/doc/effective_go#mixed-caps) is the convention.

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +		log.Fatalf("Failed creating file: %s", err)
```suggestion
		log.Fatalf("failed to create zip file: %v", err)
```

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +	zip_writer := zip.NewWriter(zip_file)
Rename this to "zipWriter", [mixedCaps](https://go.dev/doc/effective_go#mixed-caps) is the convention.

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +		log.Fatal(err)
```suggestion
		log.Fatalf("failed to close zip writer: %v", err)
```

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +// method.
```suggestion
// main packs the local corpus as <fuzzer_name>_seed_corpus.zip, which is used by OSS-Fuzz to seed remote fuzzing of the MongoDB Go Driver. See here for more details: https://google.github.io/oss-fuzz/architecture/ 
```

2023-02-08 19:51 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +			log.Fatal(err)
```suggestion
			log.Fatalf("failed to decode file %q: %v", filePath, err)
```

2023-02-09 17:54 UTC, prestonvasquez requested changes
@manunio We don't really need the "testCase", "decodeErrorTestCase", or "parseErrorTestCase" structs. We just need a subset of the "validityTestCase" struct, I've updated the PR with some suggestions on how to refactor to remove these structs.

2023-02-09 17:54 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +}
```suggestion
type validityTestCase struct {
	Description       string  `json:"description"`
	CanonicalExtJSON  string  `json:"canonical_extjson"`
	RelaxedExtJSON    *string `json:"relaxed_extjson"`
	DegenerateExtJSON *string `json:"degenerate_extjson"`
	ConvertedExtJSON  *string `json:"converted_extjson"`
}
```

2023-02-09 17:54 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +		seedTestCase(zw, &tcase)
```suggestion
		tc := struct {
			Valid []*validityTestCase `json:"valid"`
		}{}

		if err := json.NewDecoder(file).Decode(&tc); err != nil {
			log.Fatalf("failed to decode file %q: %v", filePath, err)
		}

		seedTestCase(zw, tc.Valid)
```

2023-02-09 17:54 UTC, prestonvasquez commented on cmd/build-oss-fuzz-corpus/main.go
> +	for _, vtc := range tcase.Valid {
```suggestion
func seedTestCase(zw *zip.Writer, tcase []*validityTestCase) {
	for _, vtc := range tcase {
```

2023-02-13 22:51 UTC, prestonvasquez approved these changes

2023-02-22 05:05 UTC, matthewdale requested changes
One required change to support compiling with Go 1.13, which is a currently a requirement for all non-test code in the `mongo-go-driver` repo. Otherwise, looks great!

2023-02-22 20:13 UTC, matthewdale approved these changes
Looks good 👍

2023-02-23 17:01 UTC, merged

2023-02-27 16:39 UTC, matthewdale commented
@manunio I realized after merging this that the "gosec" linter complains about the `"crypto/sha1"` package because of "weak cryptographic primitive". Does the oss-fuzz integration rely on using SHA1 hashes for filenames, or can we update it to use SHA256 hashes?