fix: fixed a memory leak caused by the commandMonitor example closure.
mongodb/mongo-go-driver pull request #1180
Opened 2023-02-09 02:48 UTC by elza2

I use the CommandMonitor feature in my project and refer to the ExampleCommandMonitor example. However, there was a memory surge during the long run, and the problem was checked for a while because the closure did not clear the element in time, resulting in a memory surge leak. Specifically to complete an example, remind the user to clear in time.

2023-02-15 22:57 UTC, prestonvasquez requested changes
Thank you @elza2 for updating this example.

2023-02-15 22:57 UTC, prestonvasquez commented on event/examples_test.go
> +			delete(startedCommands, evt.RequestID)
```suggestion

			// Empty "startedCommands" for the request ID to avoid a memory leak.
			delete(startedCommands, evt.RequestID)
```

2023-02-15 22:57 UTC, prestonvasquez commented on event/examples_test.go
> +			delete(startedCommands, evt.RequestID)
```suggestion

			// Empty "startedCommands" for the request ID to avoid a memory leak.
			delete(startedCommands, evt.RequestID)
```

2023-02-20 02:09 UTC, elza2 commented
Please recode review @prestonvasquez.

2023-02-21 17:29 UTC, prestonvasquez approved these changes

2023-02-24 19:02 UTC, merged