GODRIVER-1668: specify database name empty error
mongodb/mongo-go-driver pull request #1211
Opened 2023-03-28 14:32 UTC by stephentth

## Summary

addressing this ticket https://jira.mongodb.org/browse/GODRIVER-1668 

improving error message when the database name is empty.

## Background & Motivation

after spending a quiet amount of time debugging the misleading error message, which could have been detected immediately if there where better error messages.

2023-04-12 19:12 UTC, matthewdale requested changes
@stephentth thanks for the PR! One requested change, otherwise it looks good.

2023-04-12 19:12 UTC, matthewdale commented on x/mongo/driver/operation.go
> +	ErrDatabaseNameEmpty = errors.New("database name cannot be empty")
We don't expect users to assert on this error directly, so it doesn't need to be exported.

```suggestion
	errDatabaseNameEmpty = errors.New("database name cannot be empty")
```

2023-04-12 19:12 UTC, matthewdale commented on x/mongo/driver/operation.go
> +		return ErrDatabaseNameEmpty
```suggestion
		return errDatabaseNameEmpty
```

2023-04-12 19:12 UTC, matthewdale commented on x/mongo/driver/operation_test.go
> +			{"Database", &Operation{CommandFn: cmdFn, Deployment: d}, ErrDatabaseNameEmpty},
```suggestion
			{"Database", &Operation{CommandFn: cmdFn, Deployment: d}, errDatabaseNameEmpty},
```

2023-04-12 21:22 UTC, prestonvasquez commented on x/mongo/driver/operation.go
> +	// ErrDatabaseNameEmpty occurs when database name is not provided
```suggestion
	// errDatabaseNameEmpty occurs when a database name is not provided.
```

2023-04-16 16:34 UTC, stephentth commented
@matthewdale thanks for your feedback. updated!

2023-04-17 23:22 UTC, matthewdale approved these changes
Looks good 👍

2023-04-20 21:12 UTC, merged