GODRIVER-1808
mongodb/mongo-go-driver pull request #1584
Opened 2024-03-20 18:31 UTC by qingyang-hu

GODRIVER-1808

## Summary
This PR fixes BSON's unmarshaling behavior for interfaces by passing `reflect.Value` instead of `reflect.Type`, so the actual value type contained in the interface can be used.
Especially for an interface containing a pointer, this PR unmarshals value into the pointed concrete value.

## Background & Motivation
This PR provides a more flexible way of unmarshaling and makes the behavior closer to the `JSON` package.

2024-03-20 18:33 UTC, qingyang-hu commented on bson/bsoncodec/default_value_decoders.go
> +	if !(eType.Kind() == reflect.Interface && val.Len() > 0) {
Delay the decoder retrieval for interface slice/array so each element will be decoded based on its type.

2024-04-20 02:26 UTC, matthewdale requested changes
We should update the implementation to remove the added calls to `reflect.New`, which seems to increase memory allocs in some cases. Is there a way to only pass a `reflect.Type` when we only have type information, and pass a `reflect.Value` when we have value information?

I noticed `BenchmarkUnmarshal` reports about 30% more allocations with this PR. Keep in mind that `BenchmarkUnmarshal` actually only benchmarks unmarhshaling into a `map`. `BenchmarkCodeUnmarshal`, which unmarshals into a struct, shows no difference, so it seems to be isolated to `map` unmarshaling.
```
❯ benchstat old.txt new.txt                                                                                                       
goos: darwin
goarch: arm64
pkg: go.mongodb.org/mongo-driver/bson
                                    │   old.txt   │               new.txt                │
                                    │   sec/op    │    sec/op     vs base                │
Unmarshal/simple_struct/BSON-10       3.423µ ± 0%   3.961µ ± 19%  +15.72% (p=0.000 n=10)
Unmarshal/nested_struct/BSON-10       8.605µ ± 1%   9.258µ ±  0%   +7.59% (p=0.000 n=10)
Unmarshal/deep_bson.json.gz/BSON-10   41.98µ ± 0%   46.45µ ±  1%  +10.66% (p=0.000 n=10)
Unmarshal/flat_bson.json.gz/BSON-10   41.88µ ± 1%   47.73µ ±  0%  +13.97% (p=0.000 n=10)
Unmarshal/full_bson.json.gz/BSON-10   49.61µ ± 0%   55.90µ ±  0%  +12.67% (p=0.000 n=10)
geomean                               19.14µ        21.45µ        +12.09%

                                    │   old.txt    │               new.txt                │
                                    │     B/op     │     B/op      vs base                │
Unmarshal/simple_struct/BSON-10       1.062Ki ± 0%   1.375Ki ± 0%  +29.41% (p=0.000 n=10)
Unmarshal/nested_struct/BSON-10       7.927Ki ± 0%   8.411Ki ± 0%   +6.11% (p=0.000 n=10)
Unmarshal/deep_bson.json.gz/BSON-10   30.15Ki ± 0%   33.12Ki ± 0%   +9.85% (p=0.000 n=10)
Unmarshal/flat_bson.json.gz/BSON-10   13.11Ki ± 0%   16.79Ki ± 0%  +28.09% (p=0.000 n=10)
Unmarshal/full_bson.json.gz/BSON-10   19.93Ki ± 0%   23.57Ki ± 0%  +18.27% (p=0.000 n=10)
geomean                               9.212Ki        10.87Ki       +17.97%

                                    │  old.txt   │               new.txt               │
                                    │ allocs/op  │  allocs/op   vs base                │
Unmarshal/simple_struct/BSON-10       62.00 ± 0%    86.00 ± 0%  +38.71% (p=0.000 n=10)
Unmarshal/nested_struct/BSON-10       143.0 ± 0%    178.0 ± 0%  +24.48% (p=0.000 n=10)
Unmarshal/deep_bson.json.gz/BSON-10   822.0 ± 0%   1012.0 ± 0%  +23.11% (p=0.000 n=10)
Unmarshal/flat_bson.json.gz/BSON-10   740.0 ± 0%   1030.0 ± 0%  +39.19% (p=0.000 n=10)
Unmarshal/full_bson.json.gz/BSON-10   797.0 ± 0%   1086.0 ± 0%  +36.26% (p=0.000 n=10)
geomean                               336.2         444.4       +32.16%
```

Here's a graph view of a memory profile of running `BenchmarkUnmarshal` on the previous commit, filtered to only `reflect` calls:
![Screenshot 2024-04-19 at 7 06 21 PM](https://github.com/mongodb/mongo-go-driver/assets/9760375/210e4e30-e79a-486f-9b5d-649704db2510)
And here's the same profile of the PR commit, filtered to only `reflect` calls:
![Screenshot 2024-04-19 at 7 06 30 PM](https://github.com/mongodb/mongo-go-driver/assets/9760375/31ade693-3e66-408a-96f9-025ed0304158)

The allocs from `reflect.New` grew from 0.28GB to 1GB, which seems to be the biggest change between the two profiles.

2024-05-10 21:59 UTC, prestonvasquez approved these changes
LGTM, with updates proposed by Matt.

2024-05-21 21:55 UTC, matthewdale requested changes
Looks like the additional unmarshaling allocations are fixed! One more request for a test, but everything else looks good!

2024-05-21 21:55 UTC, matthewdale commented on bson/decoder_test.go
We should add a test or a case to an existing test that asserts that this behavior works when calling `bson.Unmarshal` in addition to `TestDecodingInterfaces`.

2024-05-30 05:49 UTC, matthewdale approved these changes
Looks good! 👍

2024-05-31 23:50 UTC, prestonvasquez approved these changes

2024-06-03 13:36 UTC, merged