GODRIVER-3107 Fix leaking rttMonitor.runHellos() routine.
mongodb/mongo-go-driver pull request #1587
Opened 2024-03-29 19:40 UTC by qingyang-hu

GODRIVER-3107

## Summary
Fix the leaky `rttMonitor.runHellos()` routine when a disconnect occurs before a connection takes place.

## Background & Motivation
There is a chance that `rttMonitor.disconnect()` is called before `rttMonitor.connect()` as [described](https://github.com/mongodb/mongo-go-driver/pull/1376/files#r1375049503) in PR #1376. In that case, the [condition](https://github.com/mongodb/mongo-go-driver/blob/d41a7cc214e8ed6c229d0a80245023300296ef4c/x/mongo/driver/topology/rtt_monitor.go#L100-L102) in `disconnect()` triggers a shortcut return which makes the `runHellos()` routine impossible to be [closed](https://github.com/mongodb/mongo-go-driver/blob/d41a7cc214e8ed6c229d0a80245023300296ef4c/x/mongo/driver/topology/rtt_monitor.go#L164).

2024-03-29 19:52 UTC, qingyang-hu commented on x/mongo/driver/topology/server.go
> +	s.rttMonitor.disconnect()
It does not cause any actual impact whether or not this line is moved. I put it here as a "fail-safe" that the disconnecting happens after the `update()` exits, so `rttMonitor.connect()` is more likely to be called beforehand.

2024-04-17 22:38 UTC, matthewdale requested changes

2024-04-18 19:55 UTC, matthewdale approved these changes
Looks good! 👍

2024-04-22 15:50 UTC, prestonvasquez approved these changes

2024-04-22 16:27 UTC, merged