GODRIVER-3096 Fixed perfomance CI break by running benchmark pkg not main
mongodb/mongo-go-driver pull request #1702
Opened 2024-07-14 03:33 UTC by prestonvasquez

GODRIVER-3096

## Summary

Change benchmark go.mod file to remove toolchain and downgrade to minimum supported version Go 1.18

## Background & Motivation

The changes made in https://github.com/mongodb/mongo-go-driver/commit/b524a7e99d7955920537d87f54a6c53db913b45a no longer work with the performance CI test. Additionally, we should be using the minimum supported version 1.18.

2024-07-15 18:18 UTC, timothy-kim-mongo reviewed
Reran failed test for 8.0 RHEL [test-sharded-auth-ssl-zlib-compression](https://spruce.mongodb.com/task/mongo_go_driver_tests_rhel_42_plus_zlib_zstd_support__version~8.0_os_ssl_40~rhel87_64_go_1_20_test_sharded_auth_ssl_zlib_compression_patch_b79eac454a0c1d3c8e7c55ff723455b6af8cc5d2_669348a6ed8a8e00075ddb64_24_07_14_03_40_23?execution=0) which passed after rerun. LGTM!

2024-07-16 17:45 UTC, timothy-kim-mongo submitted a review, later dismissed

2024-07-16 18:04 UTC, timothy-kim-mongo requested changes

2024-07-16 18:04 UTC, timothy-kim-mongo commented on internal/cmd/benchmark/go.mod
```
Compile Check Error found: [2024/07/15 19:08:02.423] ../../../../../../pkg/mod/github.com/klauspost/compress@v1.17.8/zstd/dict.go:492:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
[2024/07/15 19:08:02.423] note: module requires Go 1.20
```
from [Evergreen Patch Error](https://spruce.mongodb.com/task/mongo_go_driver_build_check_go1.18_build_patch_dbbbae75b9b8ceed1e8c270632573eac83716c8b_66957066a082750007c61c57_24_07_15_18_54_35/logs?execution=0).

It seems from this error that the compress package used at v1.17.8 only works for Go 1.20. I suggest to change the version to `github.com/klauspost/compress v1.13.6` used in GODRIVER v1 which is compatible with Go 1.18 or a possible later version that can work with go version 1.18.

2024-07-16 18:37 UTC, prestonvasquez commented on internal/cmd/benchmark/go.mod
Great catch!

2024-07-16 19:28 UTC, timothy-kim-mongo approved these changes
LGTM!

2024-07-19 19:24 UTC, matthewdale approved these changes
Looks good! 👍

2024-07-19 20:17 UTC, merged