GODRIVER-3278
mongodb/mongo-go-driver pull request #1712
Opened 2024-07-24 19:27 UTC by blink1073

GODRIVER-3278

## Summary

Port OIDC functionality to master.

2024-07-31 01:41 UTC, matthewdale requested changes

2024-07-31 01:41 UTC, matthewdale commented on mongo/collection.go
> +		fmt.Println(err)
Remove debugging `Println`.
```suggestion
```

P.S. Looks like this is in `v1` also. I'll open a PR to remove that line in `v1`.

2024-07-31 01:45 UTC, matthewdale commented on mongo/collection.go
> +		fmt.Println(err)
PR for v1: https://github.com/mongodb/mongo-go-driver/pull/1722

2024-07-31 20:56 UTC, matthewdale submitted a review, later dismissed
Looks good! 👍

2024-08-01 00:44 UTC, blink1073 commented
I had to address a few import and lint failures since your review.

2024-08-01 16:12 UTC, matthewdale approved these changes

2024-08-01 16:38 UTC, merged