GODRIVER-2617 Remove deprecated code
mongodb/mongo-go-driver pull request #1716
Opened 2024-07-25 20:14 UTC by qingyang-hu

GODRIVER-2617
GODRIVER-3142

## Summary
Remove all remaining deprecated code including unexporting `bson.DefaultRegistry`.

## Background & Motivation

2024-07-26 02:02 UTC, matthewdale requested changes

2024-07-26 17:02 UTC, prestonvasquez submitted a review, later dismissed

2024-07-29 22:49 UTC, matthewdale approved these changes
Looks good! 👍

2024-07-30 16:49 UTC, prestonvasquez approved these changes

2024-07-30 16:51 UTC, merged