GODRIVER-3168 Retry KMS requests on transient errors.
mongodb/mongo-go-driver pull request #1887
Opened 2024-11-11 15:40 UTC by qingyang-hu

GODRIVER-3168

## Summary
Retry KMS requests on transient errors.

## Background & Motivation

2024-12-04 21:15 UTC, kevinAlbs commented on x/mongo/driver/crypt.go
> +			if kmsCtx.Fail() {
See MONGOCRYPT-752. When `mongocrypt_kms_ctx_fail` returns false, consider wrapping the error message from `mongocrypt_ctx_kms_status`. The error from `mongocrypt_ctx_kms_status` may help identify a retry occurred (e.g. "KMS request failed after 3 retries due to a network error: last attempt failed with: <driver error>")

2025-01-14 01:23 UTC, prestonvasquez requested changes

2025-01-15 18:24 UTC, prestonvasquez reviewed
LGTM with minor edit

2025-01-15 18:24 UTC, prestonvasquez commented on internal/integration/client_side_encryption_prose_test.go
> +					assert.NoError(mt, err, "error in Encrypt: %v", err)
```suggestion
					require.NoError(mt, err, "error in Encrypt: %v", err)
```

2025-01-15 22:29 UTC, prestonvasquez approved these changes

2025-01-17 04:14 UTC, matthewdale commented on .evergreen/config.yml
> +        args: ["-u", "${DRIVERS_TOOLS}/.evergreen/csfle/kms_failpoint_server.py", "--port", "9003"]
This step is already done by [start-servers.sh](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/d8098d27d0a94afe6ed20b01d653404ba6dd3910/.evergreen/csfle/start-servers.sh#L76).

2025-01-17 04:14 UTC, matthewdale commented on .evergreen/config.yml
> +  start-kms-failpoint-server:
This function seems like mostly a duplicate of `start-cse-servers`. Can we use that existing function instead of this one?

2025-01-17 04:14 UTC, matthewdale commented on internal/integration/client_side_encryption_prose_test.go
> +	mt.RunOpts("24. kms retry tests", noClientOpts, func(mt *mtest.T) {
Optional: Consider separating this into its own test function.

2025-01-17 04:14 UTC, matthewdale commented on .evergreen/config.yml
> +      - name: ".retry-kms-requests"
Instead of making a new matrix, can we roll this up into a general "KMS Test" that contains all ".kms-tls" and ".retry-kms-requests" tests?

2025-02-07 03:23 UTC, matthewdale approved these changes
Looks good! 👍

2025-02-07 17:00 UTC, merged