GODRIVER-3086 Add ErrorCodes to ServerError API
mongodb/mongo-go-driver pull request #1894
Opened 2024-11-15 22:28 UTC by prestonvasquez

GODRIVER-3086

## Summary

Extend the `ServerError` interface to include `ErrorCodes` which will return a list of deduplicated error codes returned by the server during the lifetime of operation execution. 

## Background & Motivation

The Go Driver provides a way to check if a ServerError has a specific error code, but no way to determine all error codes that occurred during the operation.

2024-11-18 15:52 UTC, FGasper reviewed
Thank you for this! :)

2024-11-18 15:52 UTC, FGasper commented on mongo/errors.go
> +	// server.
It’d be good to mention if there’s a defined sort order.

2024-11-18 15:52 UTC, FGasper commented on mongo/errors.go
> +// ErrorCodes returns a list of error codes returned by the server.
It’d be good to mention if there’s a defined sort order.

2024-11-18 15:52 UTC, FGasper commented on mongo/errors.go
> +	// Deduplicate error codes.
Not that it affects us :), but: I see the same logic here and in WriteException’s method. This seems like the sort of thing you’d deduplicate.

2025-01-17 03:56 UTC, matthewdale commented on mongo/errors.go
> +	}
Do we need to deduplicate error codes? If the server returns the same error for multiple ops, it might be useful to see multiple of the same error codes. Users who want a deduplicated view of errors can do that logic themselves.

2025-01-17 03:56 UTC, matthewdale commented on mongo/errors.go
> +	return hasErrorCode(e, code)
Re-implementing this in terms of `ErrorCodes` seems like an unnecessary change. The existing code is still valid and is more obvious.

2025-01-17 03:56 UTC, matthewdale commented on mongo/errors.go
> +	return hasErrorCode(we, code)
Re-implementing this in terms of `ErrorCodes` seems like an unnecessary change. The existing code is still valid and is more obvious.

2025-01-22 01:41 UTC, matthewdale approved these changes
Looks good! 👍

2025-01-22 01:41 UTC, matthewdale commented on mongo/errors.go
> +	// ErrorCodes returns a deduplicated list of error codes returned by the
The latest revision does not deduplicate error codes.

```suggestion
	// ErrorCodes returns a list of error codes returned by the
```

2025-01-29 19:21 UTC, FGasper requested changes
I’ve made a few suggestions on verbiage; see what you think.

Also: are there any cases where it is, in fact, correct just to check HasErrorCode() without also checking for _other_, unexpected error codes? If not, should HasErrorCode()’s documentation also be updated to discourage its use?

Basically ISTM that anyplace an application calls `HasErrorCode(123)` should instead be a check of whether ErrorCodes()’s return contains _solely_ 123. Is that reasonable?

2025-01-29 19:21 UTC, FGasper commented on mongo/errors.go
> +	// server.
@prestonvasquez Thoughts?

2025-01-29 19:21 UTC, FGasper commented on mongo/errors.go
> +	// server.
Also, I suggest:
> ErrorCodes returns all error codes (unsorted) in the server’s response. This includes nested errors (e.g., write concern errors) as well as the top-level error code.

2025-01-29 19:21 UTC, FGasper commented on mongo/errors.go
> +// ErrorCodes returns a list of error codes returned by the server.
> ErrorCodes returns all error codes (unsorted) in the server’s response. This includes nested errors (e.g., write concern errors) as well as the top-level error code.

2025-01-29 20:09 UTC, prestonvasquez commented
@FGasper 

> I’ve made a few suggestions on verbiage; see what you think.

I agree with the changes to the interface documentation but don't think we need to be more specific on the methods.

> anyplace an application calls `HasErrorCode(123)` should instead be a check of whether ErrorCodes()’s return contains _solely_ 123. Is that reasonable?

HasErrorCode's logic has not changed and so we should maintain the current intentions and usage guidelines for our users. The current documentation correctly expresses the purpose of the method for each error type.

2025-01-29 20:12 UTC, FGasper approved these changes
LGTM. Thanks!

2025-01-30 04:38 UTC, matthewdale commented
@FGasper I believe there are plenty of cases where `HasErrorCode` is sufficient, especially for single-read or single-write operations (i.e. non-bulk operations). I think it would be confusing to discourage its use.

2025-01-30 13:59 UTC, FGasper commented
I’ve moved the `HasErrorCode` discussion to Slack.

2025-01-30 16:14 UTC, merged