GODRIVER-3434 Revert builder-lister pattern for client options
mongodb/mongo-go-driver pull request #1899
Opened 2024-11-21 19:51 UTC by prestonvasquez

GODRIVER-3434

## Summary

Don't apply the builder-lister pattern for client options.

## Background & Motivation

This update has been a source of frustration for users migrating to the v2 beta. While the lister-builder pattern is effective for operational options, client options are often defined as struct literals and used in test / general comparison within a users code. For example:

```go
opts := options.Client().SetAppName("x")

// ...

if opts.AppName != nil && opts.AppName == "x" {
    // do something
}
```

While this isn't too difficult to manage in v2, it does require a code change. The primarily discussed alternative is to apply a `Merge` function to `ClientOptionsBuilder`. However, this would still require a code change and is kind of confusing for people who aren't familiar with the history of the problem in the Go Driver. This PR suggests deferring that question to v3, as client options are rather unique.

2024-12-03 23:12 UTC, qingyang-hu approved these changes
LGTM

2024-12-04 03:46 UTC, matthewdale commented on mongo/options/clientoptions.go
> +func (c *ClientOptions) SetAutoEncryptionOptions(aeopts Lister[AutoEncryptionOptions]) *ClientOptions {
For `AutoEncryptionOptions`, `LoggerOptions`, and `ServerAPIOptions`, should we also revert to the previous pattern (i.e. not use of `Lister` type)?

2024-12-04 21:41 UTC, matthewdale approved these changes
Looks good! 👍

2024-12-04 21:53 UTC, qingyang-hu commented on mongo/options/serverapioptions.go
> +// serverAPIversion.// ServerAPI creates a new ServerAPIOptions configured with the provided serverAPIversion.
``` suggestion
// serverAPIversion.
```

2024-12-04 21:55 UTC, qingyang-hu commented on mongo/client.go
> +// Copyright (C) MongoDB, Inc. 2017-present.
``` suggestion
// Copyright (C) MongoDB, Inc. 2017-present.
//
```

2024-12-04 21:57 UTC, qingyang-hu requested changes
It looks good other than some typos.

2024-12-04 22:01 UTC, qingyang-hu approved these changes
👍

2024-12-04 22:57 UTC, matthewdale approved these changes

2024-12-05 00:00 UTC, merged