GODRIVER-1870 Remove insertedCount assertions on insertOne
mongodb/mongo-go-driver pull request #691
Opened 2021-06-25 21:47 UTC by benjirewis

GODRIVER-1870

Assertions for `insertedCount` were recently removed from `insertOne-dots_and_dollars`, as "insertedCount" is not part of the specification for `insertOne`. Remove assertions from spec test and remove workaround for hardcoding `insertedCount` of 1 into `executeInsertOne` result.

2021-06-25 21:52 UTC, kevinAlbs approved these changes
LGTM

2021-06-25 21:53 UTC, benjirewis commented
Will wait for tests before merging.

2021-07-02 13:35 UTC, jmikola commented
@benjirewis: Copying my comment from JIRA:

> Since this is still in review, I also linked it up with DRIVERS-1828, which is a follow-up change for DRIVERS-1237. The description for DRIVERS-1237 was also updated to refer to the new sync target: https://github.com/mongodb/specifications/commit/44f83106033a609f2af40e3e4d99852a03096ba5

2021-07-02 13:36 UTC, jmikola requested changes
@benjirewis: Copying my comment from JIRA:

> Since this is still in review, I also linked it up with DRIVERS-1828, which is a follow-up change for DRIVERS-1237. The description for DRIVERS-1237 was also updated to refer to the new sync target: https://github.com/mongodb/specifications/commit/44f83106033a609f2af40e3e4d99852a03096ba5

2021-07-12 16:00 UTC, kevinAlbs approved these changes

2021-07-12 16:42 UTC, merged