GODRIVER-2237: Run KMS KMIP spec and prose tests in Evergreen
mongodb/mongo-go-driver pull request #816
Opened 2021-11-18 22:56 UTC by gabbyasuncion

[GODRIVER-2237](https://jira.mongodb.org/browse/GODRIVER-2237)

Configures an Evergreen build variant to test the KMS KMIP spec and prose tests. Passes according to [this patch](https://spruce.mongodb.com/version/6196d83161837d799a22ece1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

2021-11-19 15:08 UTC, benjirewis requested changes
Great work! Evergreen is complaining about your `config.yml` file being invalid; it's because of alignment issues. See my "suggested change" comments on how to fix that. Can you also reconfigure the associated patch to run `KMS KMIP Ubuntu 18.04` so we can see that it succeeds?

2021-11-19 15:08 UTC, benjirewis commented on .evergreen/config.yml
> +     - command: shell.exec
```suggestion
    - command: shell.exec
```

2021-11-19 15:08 UTC, benjirewis commented on .evergreen/config.yml
> +          pip install git+https://github.com/kevinAlbs/PyKMIP.git@expand_tls12_ciphers
Can we leave a comment (`#`) above this `pip install` with a TODO and an associated GODRIVER ticket on stabilizing this `pip install` (not installing directly from @kevinAlbs' branch) once [this PR](https://github.com/OpenKMIP/PyKMIP/pull/659) is merged?

2021-11-19 15:08 UTC, benjirewis commented on .evergreen/config.yml
> +  - command: shell.exec
```suggestion
    - command: shell.exec
```

2021-11-19 15:08 UTC, benjirewis commented on .evergreen/config.yml
> +    - name: "test-kms-kmip"
```suggestion
  - name: "test-kms-kmip"
```

2021-11-19 21:53 UTC, benjirewis approved these changes
Great job! 🧑‍🔧

2021-11-19 22:58 UTC, kevinAlbs reviewed
LGTM with a typo fix.

2021-11-19 22:58 UTC, kevinAlbs commented on Makefile
> +evg-test-kmip:
No need to change now. These tests are not specific to KMIP. I think `evg-test-kmip` with `evg-test-kms` can be combined in a future PR.

2021-11-19 23:53 UTC, gabbyasuncion commented on .evergreen/config.yml
> +          make evg-test-kms \
Thanks for catching that!

2021-11-22 16:56 UTC, benjirewis commented
As discussed offline, let's first merge PR #812 once you're done addressing comments there, rebase this PR on master, and make sure that the new/updated client-side-encryption tests are skipped on every task besides `test-kms-kmip` (since the correct servers will not be running) and pass on `test-kms-kmip` (where the correct servers are running).

2021-11-22 18:15 UTC, kevinAlbs commented
> As discussed offline, let's first merge PR #812 once you're done addressing comments there, rebase this PR on master, and make sure that the new/updated client-side-encryption tests are skipped on every task besides `test-kms-kmip` (since the correct servers will not be running) and pass on `test-kms-kmip` (where the correct servers are running).

SGTM. A possible way to do this is to set an environment variable in the `test-kms-kmip` task. And skip the tests that are run as part of the `test-kms-kmip` task if that environment variable is not set:

Example with the `TestClientSideEncryptionSpec/kmipKMS` test. Update `client_side_encryption_spec.go`:

```diff
        for _, fileName := range jsonFilesInDir(t, path.Join(dataPath, encryptionSpecName)) {
                t.Run(fileName, func(t *testing.T) {
+                       if fileName == "kmipKMS.json" && "" == os.Getenv("KMS_MOCK_SERVERS_RUNNING") {
+                               t.Skipf("Skipping test as KMS_MOCK_SERVERS_RUNNING is not set")
+                       }
                        runSpecTestFile(t, encryptionSpecName, fileName)
                })
        }
```

2021-11-23 16:46 UTC, benjirewis approved these changes
LGTM even more!

2021-11-23 16:50 UTC, kevinAlbs approved these changes
LGTM!

2021-11-23 16:57 UTC, merged