GODRIVER-2309 Convert sessions spec tests to unified test format
mongodb/mongo-go-driver pull request #998
Opened 2022-06-23 19:46 UTC by prestonvasquez

[GODRIVER-2300](https://jira.mongodb.org/browse/GODRIVER-2309)

- Delete sessions/legacy directory 
- Unify sessions/*
- Deprecate legacy integration test runners

2022-06-23 21:00 UTC, benjirewis requested changes
Yay! Love these conversions.

2022-06-23 21:00 UTC, benjirewis commented on mongo/integration/unified_spec_test.go
> +// ! this entire function probably goes away
I think you probably left this in by accident. I assume the legacy transactions tests still use this?

2022-06-24 23:47 UTC, benjirewis approved these changes

2022-06-27 19:27 UTC, matthewdale approved these changes
Looks good 👍

2022-06-27 22:55 UTC, merged